version: '3.8'

services:
  registry:
    image: registry:latest
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/ca.pem
      REGISTRY_HTTP_TLS_KEY: /certs/cert-key.pem
    volumes:
      - /home/server3/docker-registry/certs:/certs
      - /home/server3/docker-registry/auth:/auth
